version: '3'

services:
  keycloak:
    image: mykeycloak:latest
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # 使用宿主機的 PostgreSQL
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/${POSTGRES_DB}
    ports:
      - "8443:8443"
      - "9000:9000"
      - "8080:8080"
    command: ["start", "--optimized"]